name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Triggers workflow on push to main branch
  workflow_dispatch:
# Grant permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite outputs build files to 'dist' (use 'build' if using CRA)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  run-cypress-test:
    # needs: [wait_amplify_build_complete, setup_for_cypress]
    uses: bdle/cy-mortgage-calulator/.github/workflows/reusable_workflow.yml@main
    secrets: inherit
    with:
      test_suite: 'tier1'
      dispatcher_text: 'Atto Mattic from mortgage-calculator repo'
  
  package-sent-jfrog:
    needs: run-cypress-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
      # 4. Package build folder into a .zip bundle
      - name: Compress Build Artifact
        run: |
          zip -r mortgage-calculator-v${{ github.run_number }}.zip dist/

      # 5. Setup official JFrog CLI
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # 6. Upload build artifact to Artifactory Generic Repository
      - name: Upload Artifact to JFrog
        run: |
          jf rt upload mortgage-calculator-v${{ github.run_number }}.zip mortgage-calculator-builds/